=== DerDavid/wba2-2013/wba2ss2013phase1/src/aufgabe3/Rezept.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
			elementFormDefault="qualified" 
			targetNamespace="http://example.org/Rezept"
			xmlns:tn="http://example.org/Rezept"> 
			
			
	<xs:element name="recipe">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="tn:ctrecipe">
					<xs:attribute name="id" type="tn:minInclInt" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
  
	<xs:complexType name="ctrecipe">
	  	<xs:sequence>
	  		<xs:element name="title">
	  			<xs:simpleType>
	  				<xs:restriction base="xs:string">
	  					<xs:minLength value="3"/>
	  					<xs:maxLength value="75"/>
	  				</xs:restriction>
	  			</xs:simpleType>
	  		</xs:element>
	  		<xs:element name="picture" type="xs:anyURI" minOccurs="0" maxOccurs="unbounded"/>
	  		<xs:element name="ingredient" type="tn:ctingredient" minOccurs="1" maxOccurs="unbounded"/>
	  		<xs:element name="portions" type="tn:minInclInt" minOccurs="1"/>
	  		<xs:element name="preparation" type="tn:ctpreparation" minOccurs="1"/>
	  		<xs:element name="comments" type="tn:ctcomments" minOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="ctingredient">
	  	<xs:simpleContent>
	  		<xs:extension base="xs:string">
	  			<xs:attribute name="name" type="xs:string" use="required"/>
	  			<xs:attribute name="amount" type="tn:minInclDeci" use="required"/>
	  			<xs:attribute name="unit" type="tn:unitIngredient" use="optional"/>
	  		</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	  
	<xs:complexType name="ctpreparation">
	  	<xs:sequence>
	  		<xs:element name="preptime">
	  			<xs:complexType>
	  				<xs:simpleContent>
	  					<xs:extension base="tn:minInclDeci">
	  						<xs:attribute name="unit" type="tn:unitTime" use="required"/>
	  					</xs:extension>
	  				</xs:simpleContent>
	  			</xs:complexType>
	  		</xs:element>
	  		<xs:element name="difficulty" type="tn:difficulty" />
	  		<xs:element name="calvalue" type="tn:minInclInt" />
			<xs:element name="text" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	  
	<xs:complexType name="ctcomments">
		<xs:sequence>
	  		<xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
	  			<xs:complexType>
		  			<xs:complexContent>
		  				<xs:extension base="tn:ctentry">
		  					<xs:attribute name="id" type="tn:minInclInt" use="required"/>
		  				</xs:extension>
		  			</xs:complexContent>
	  			</xs:complexType>	
			</xs:element>	
		</xs:sequence>
	</xs:complexType>
	  
	<xs:complexType name="ctentry">
	  	<xs:sequence>		
			<xs:element name="author" type="xs:string"/>
		  	<xs:element name="date" type="xs:dateTime"/>
		  	<xs:element name="text" type="xs:string"/>
	  	</xs:sequence>
	</xs:complexType>
	
	<!-- simpleTypes -->
	 
	<xs:simpleType name="minInclDeci">
	 	<xs:restriction base="xs:decimal">
	 		<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="minInclInt">
	 	<xs:restriction base="xs:integer">
	 		<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="unitIngredient">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Msp."/>
			<xs:enumeration value="cm"/>
			<xs:enumeration value="mg"/>
			<xs:enumeration value="g"/>
			<xs:enumeration value="dg"/>
			<xs:enumeration value="kg"/>
			<xs:enumeration value="cl"/>
			<xs:enumeration value="ml"/>
			<xs:enumeration value="dl"/>
			<xs:enumeration value="EL"/>
			<xs:enumeration value="EL, gest."/>
			<xs:enumeration value="TL"/>
			<xs:enumeration value="TL, gest."/>
			<xs:enumeration value="Pkt."/>
			<xs:enumeration value="n.B."/>
			<xs:enumeration value="e. Stiele"/>
			<xs:enumeration value="evt."/>
			<xs:enumeration value="gr. Dose"/>
			<xs:enumeration value="gr. Fl."/>
			<xs:enumeration value="kl. Dose"/>
			<xs:enumeration value="Port"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="unitTime">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Min"/>
			<xs:enumeration value="Std"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="difficulty">
		<xs:restriction base="xs:string">
			<xs:enumeration value="einfach"/>
	  		<xs:enumeration value="normal"/>
	  		<xs:enumeration value="schwer"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== DerDavid/wba2-2013/wba2ss2013phase1/src/aufgabe3/Rezept.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recipe xmlns="http://example.org/Rezept" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="24641006006067" xsi:schemaLocation="http://example.org/Rezept Rezept.xsd">
    <title>Lenchen's Schokoladenkuchen</title>
    <picture>http://static.chefkoch-cdn.de/ck.de/rezepte/2/2464/8082-960x720-lenchen_s_schokoladenkuchen.jpg</picture>
    <ingredient unit="g" amount="200" name="Butter"></ingredient>
    <ingredient unit="g" amount="200" name="Zucker"></ingredient>
    <ingredient unit="g" amount="200" name="Schokolade, Blockschokolade"></ingredient>
    <ingredient unit="g" amount="150" name="Mehl"></ingredient>
    <ingredient unit="TL" amount="0.5" name="Backpulver"></ingredient>
    <ingredient unit="Pkt." amount="1" name="Vanillezucker"></ingredient>
    <ingredient amount="4" name="Eier"></ingredient>
    <portions>16</portions>
    <preparation>
        <preptime unit="Std">1</preptime>
        <difficulty>normal</difficulty>
        <calvalue>295</calvalue>
        <text>Butter und Schokolade im Wasserbad schmelzen. Eier trennen. Eiweiß steif schlagen. Eigelbe, Zucker und Vanillezucker verrühren. Geschmolzene Butter-Schokomasse hinzufügen und mischen. Mehl mit dem Backpulver in die Masse sieben und zum Schluss die steifen Eiweiße vorsichtig unterheben. In eine gut gefettete Form geben. Bei 180°Grad 40 - 50 Minuten backen.
		</text>
    </preparation>
    <comments>
        <entry id="1403">
            <author>swieselchen</author>
            <date>2002-02-07T16:49:00.000+02:00</date>
            <text>Habe Deinen Kuchen gestern gebacken (kleine Abwandlung: statt Blockschokolade hatte ich nur Kuvertüre, zartbitter und ich habe noch etwas Rumaroma und eine Prise Salz dazugegeben) mein LAG war total begeistert. Ich übrigends auch, super Rezept.</text>
        </entry>
        <entry id="7243">
            <author>Mane</author>
            <date>2003-01-07T15:06:00.000+02:00</date>
            <text>Habe ihn eben gebacken und bin begeistert.Super Rezept:-)</text>
        </entry>
        <entry id="7244">
            <author>Max Mustermann</author>
            <date>2013-04-10T16:09:00.000+02:00</date>
            <text>Hallo</text>
        </entry>
        <entry id="7245">
            <author>Test</author>
            <date>2013-04-13T13:26:09.095+02:00</date>
            <text>Test</text>
        </entry>
    </comments>
</recipe>

=== DerDavid/wba2-2013/wba2ss2013phase1/bin/aufgabe3/Rezept2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tn:recipe id="0" xmlns:tn="http://example.org/Rezept" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://example.org/Rezept Rezept.xsd ">
  <tn:title>tn:title</tn:title>
  <tn:ingredient amount="0.0" name="">tn:ingredient</tn:ingredient>
  <tn:portions>0</tn:portions>
  <tn:preparation>
    <tn:preptime unit="Min">0.0</tn:preptime>
    <tn:difficulty>einfach</tn:difficulty>
    <tn:calvalue>0</tn:calvalue>
    <tn:text>tn:text</tn:text>
  </tn:preparation>
  <tn:comments/>
</tn:recipe>
